name: build-docker

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      packages: write
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - variant: core
            image_tag: latest
            sync_args: --no-dev

          - variant: discord
            image_tag: discord
            sync_args: --no-dev --extra discord

          - variant: api
            image_tag : api
            sync_args: --no-dev --extra api
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/andyjjrt/nanobot
          tags: |
            type=pep440,pattern={{version}}
      -
        name: Login to ghcr.io
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          build-args: |
            UV_SYNC_ARGS=${{ matrix.sync_args }}
          tags: |
            ghcr.io/andyjjrt/nanobot:${{ matrix.image_tag }}
            ghcr.io/andyjjrt/nanobot:${{ github.ref_name }}-${{ matrix.variant }}
  release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write

    steps:
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ github.ref_name }}
          tag: ${{ github.ref_name }}
          prerelease: ${{ contains(github.ref_name, 'beta') }}
          body: |
            # ${{ github.ref_name }}

            ## Docker images

            ```sh
            docker pull ghcr.io/${{ github.repository }}:latest
            docker pull ghcr.io/${{ github.repository }}:discord
            docker pull ghcr.io/${{ github.repository }}:api
            ```

            ## Versioned tags

            ```sh
            docker pull ghcr.io/${{ github.repository }}:${{ github.ref_name }}-core
            docker pull ghcr.io/${{ github.repository }}:${{ github.ref_name }}-discord
            docker pull ghcr.io/${{ github.repository }}:${{ github.ref_name }}-api
            ```

            ## Release Note

            [HKUDS/nanobot](https://github.com/HKUDS/nanobot/releases/tag/${{ github.ref_name }})